// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zapas.Api.Data;

#nullable disable

namespace Zapas.Api.Migrations
{
    [DbContext(typeof(ZapasDbContext))]
    [Migration("20260723191658_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Zapas.Api.Entities.RunIntervalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte?>("AverageHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AveragePaceSecondsPerKm")
                        .HasColumnType("REAL");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("LapNumber")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("MaxHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("RunIntervals", (string)null);
                });

            modelBuilder.Entity("Zapas.Api.Entities.SessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte?>("AverageHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AveragePaceSecondsPerKm")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("MaxHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalDistanceMeters")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("TotalDuration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("StartTime");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("Zapas.Api.Entities.RunIntervalEntity", b =>
                {
                    b.HasOne("Zapas.Api.Entities.SessionEntity", "Session")
                        .WithMany("Intervals")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Zapas.Api.Entities.SessionEntity", b =>
                {
                    b.Navigation("Intervals");
                });
#pragma warning restore 612, 618
        }
    }
}
